import { Subject, Quiz, Assignment, Grade, Chapter } from "./types";

export const currentUser = {
  id: "u1",
  name: "Ahmad Fadhil",
  email: "fadhil@email.com",
  role: "siswa" as const,
  avatar: undefined,
};

export const subjects: Subject[] = [
  {
    id: "s1",
    name: "Matematika",
    icon: "Calculator",
    color: "oklch(0.55 0.15 180)",
    chaptersCount: 8,
    progress: 65,
    description: "Aljabar, Geometri, Statistika, dan Kalkulus Dasar",
  },
  {
    id: "s2",
    name: "Bahasa Indonesia",
    icon: "BookOpen",
    color: "oklch(0.6 0.14 160)",
    chaptersCount: 6,
    progress: 80,
    description: "Tata Bahasa, Sastra, dan Keterampilan Menulis",
  },
  {
    id: "s3",
    name: "Fisika",
    icon: "Atom",
    color: "oklch(0.5 0.14 200)",
    chaptersCount: 7,
    progress: 40,
    description: "Mekanika, Termodinamika, dan Gelombang",
  },
  {
    id: "s4",
    name: "Biologi",
    icon: "Leaf",
    color: "oklch(0.6 0.16 145)",
    chaptersCount: 9,
    progress: 55,
    description: "Sel, Genetika, Ekologi, dan Evolusi",
  },
  {
    id: "s5",
    name: "Bahasa Inggris",
    icon: "Globe",
    color: "oklch(0.55 0.12 250)",
    chaptersCount: 5,
    progress: 90,
    description: "Grammar, Reading, Writing, dan Conversation",
  },
  {
    id: "s6",
    name: "Kimia",
    icon: "FlaskConical",
    color: "oklch(0.6 0.15 60)",
    chaptersCount: 6,
    progress: 30,
    description: "Struktur Atom, Ikatan Kimia, dan Reaksi Kimia",
  },
];

export const chapters: Chapter[] = [
  {
    id: "c1",
    subjectId: "s1",
    title: "Bab 1: Aljabar Linear",
    subChapters: [
      { id: "sc1", chapterId: "c1", title: "Persamaan Linear Satu Variabel", type: "text", duration: "15 menit", completed: true },
      { id: "sc2", chapterId: "c1", title: "Persamaan Linear Dua Variabel", type: "video", duration: "20 menit", completed: true },
      { id: "sc3", chapterId: "c1", title: "Sistem Persamaan Linear", type: "pdf", duration: "25 menit", completed: false },
    ],
  },
  {
    id: "c2",
    subjectId: "s1",
    title: "Bab 2: Geometri Dasar",
    subChapters: [
      { id: "sc4", chapterId: "c2", title: "Bangun Datar", type: "text", duration: "20 menit", completed: true },
      { id: "sc5", chapterId: "c2", title: "Bangun Ruang", type: "video", duration: "30 menit", completed: false },
      { id: "sc6", chapterId: "c2", title: "Luas dan Volume", type: "pdf", duration: "15 menit", completed: false },
    ],
  },
  {
    id: "c3",
    subjectId: "s1",
    title: "Bab 3: Statistika",
    subChapters: [
      { id: "sc7", chapterId: "c3", title: "Mean, Median, Modus", type: "text", duration: "20 menit", completed: false },
      { id: "sc8", chapterId: "c3", title: "Penyajian Data", type: "video", duration: "25 menit", completed: false },
    ],
  },
];

export const quizzes: Quiz[] = [
  {
    id: "q1",
    subjectId: "s1",
    title: "Kuis Aljabar Linear",
    questionCount: 10,
    timeLimit: 15,
    bestScore: 85,
    attempts: 2,
    type: "pilihan_ganda",
  },
  {
    id: "q2",
    subjectId: "s1",
    title: "Kuis Geometri Dasar",
    questionCount: 8,
    timeLimit: 12,
    bestScore: undefined,
    attempts: 0,
    type: "pilihan_ganda",
  },
  {
    id: "q3",
    subjectId: "s2",
    title: "Kuis Tata Bahasa",
    questionCount: 15,
    timeLimit: 20,
    bestScore: 92,
    attempts: 1,
    type: "benar_salah",
  },
  {
    id: "q4",
    subjectId: "s3",
    title: "Kuis Mekanika Newton",
    questionCount: 10,
    timeLimit: 15,
    bestScore: 70,
    attempts: 3,
    type: "pilihan_ganda",
  },
];

export const assignments: Assignment[] = [
  {
    id: "a1",
    subjectId: "s1",
    title: "Tugas Aljabar: Sistem Persamaan",
    description: "Kerjakan soal nomor 1-10 pada buku halaman 45. Tuliskan langkah-langkah penyelesaiannya dengan rapi.",
    deadline: "2026-05-10T23:59:00",
    status: "belum",
    maxFileSize: 10,
    allowedFormats: ["pdf", "doc", "docx", "jpg", "png"],
  },
  {
    id: "a2",
    subjectId: "s2",
    title: "Essay: Analisis Puisi",
    description: "Buatlah analisis mendalam terhadap puisi 'Aku' karya Chairil Anwar. Minimal 500 kata.",
    deadline: "2026-05-08T23:59:00",
    status: "dikumpulkan",
    maxFileSize: 10,
    allowedFormats: ["pdf", "doc", "docx"],
  },
  {
    id: "a3",
    subjectId: "s3",
    title: "Laporan Praktikum Fisika",
    description: "Susun laporan praktikum tentang Hukum Newton I, II, dan III berdasarkan percobaan yang telah dilakukan.",
    deadline: "2026-05-05T23:59:00",
    status: "dinilai",
    grade: 88,
    feedback: "Laporan sangat rapi dan analisis data sudah baik. Pertahankan!",
    maxFileSize: 10,
    allowedFormats: ["pdf"],
  },
  {
    id: "a4",
    subjectId: "s4",
    title: "Presentasi Ekosistem",
    description: "Buat presentasi tentang salah satu ekosistem di Indonesia. Minimal 15 slide.",
    deadline: "2026-05-03T23:59:00",
    status: "terlambat",
    maxFileSize: 10,
    allowedFormats: ["pdf", "pptx"],
  },
];

export const grades: Grade[] = [
  { id: "g1", subjectId: "s1", subjectName: "Matematika", type: "kuis", title: "Kuis Aljabar Linear", score: 85, maxScore: 100, date: "2026-04-20" },
  { id: "g2", subjectId: "s1", subjectName: "Matematika", type: "tugas", title: "Tugas Persamaan Linear", score: 90, maxScore: 100, date: "2026-04-15" },
  { id: "g3", subjectId: "s2", subjectName: "Bahasa Indonesia", type: "kuis", title: "Kuis Tata Bahasa", score: 92, maxScore: 100, date: "2026-04-22" },
  { id: "g4", subjectId: "s3", subjectName: "Fisika", type: "kuis", title: "Kuis Mekanika Newton", score: 70, maxScore: 100, date: "2026-04-18" },
  { id: "g5", subjectId: "s3", subjectName: "Fisika", type: "tugas", title: "Laporan Praktikum", score: 88, maxScore: 100, date: "2026-04-25" },
  { id: "g6", subjectId: "s4", subjectName: "Biologi", type: "kuis", title: "Kuis Sel dan Jaringan", score: 78, maxScore: 100, date: "2026-04-10" },
  { id: "g7", subjectId: "s5", subjectName: "Bahasa Inggris", type: "kuis", title: "Grammar Quiz", score: 95, maxScore: 100, date: "2026-04-23" },
  { id: "g8", subjectId: "s5", subjectName: "Bahasa Inggris", type: "tugas", title: "Essay Writing", score: 88, maxScore: 100, date: "2026-04-28" },
  { id: "g9", subjectId: "s1", subjectName: "Matematika", type: "kuis", title: "Kuis Geometri", score: 76, maxScore: 100, date: "2026-04-30" },
  { id: "g10", subjectId: "s6", subjectName: "Kimia", type: "kuis", title: "Kuis Struktur Atom", score: 82, maxScore: 100, date: "2026-05-01" },
];

export const questions = [
  {
    id: "qq1",
    quizId: "q1",
    text: "Jika 2x + 3 = 11, maka nilai x adalah...",
    type: "pilihan_ganda" as const,
    options: ["2", "3", "4", "5"],
    correctAnswer: "4",
    explanation: "2x + 3 = 11 → 2x = 8 → x = 4",
  },
  {
    id: "qq2",
    quizId: "q1",
    text: "Penyelesaian dari 3(x - 2) = 12 adalah...",
    type: "pilihan_ganda" as const,
    options: ["4", "5", "6", "7"],
    correctAnswer: "6",
    explanation: "3(x-2) = 12 → x-2 = 4 → x = 6",
  },
  {
    id: "qq3",
    quizId: "q1",
    text: "Persamaan y = 2x + 1 memiliki gradien...",
    type: "pilihan_ganda" as const,
    options: ["1", "2", "3", "-1"],
    correctAnswer: "2",
    explanation: "Pada bentuk y = mx + c, gradien (m) = 2",
  },
  {
    id: "qq4",
    quizId: "q1",
    text: "Himpunan penyelesaian dari x² - 9 = 0 adalah...",
    type: "pilihan_ganda" as const,
    options: ["{3}", "{-3, 3}", "{9}", "{-9, 9}"],
    correctAnswer: "{-3, 3}",
    explanation: "x² = 9 → x = ±3, jadi HP = {-3, 3}",
  },
  {
    id: "qq5",
    quizId: "q1",
    text: "Nilai dari |−7| + |3| adalah...",
    type: "pilihan_ganda" as const,
    options: ["-4", "4", "10", "-10"],
    correctAnswer: "10",
    explanation: "|−7| = 7 dan |3| = 3, jadi 7 + 3 = 10",
  },
];
